# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from . import __version__ as app_version

app_name = "hms_tz"
app_title = "HMS TZ"
app_publisher = "Aakvatech"
app_description = "HMS TZ"
app_icon = "octicon octicon-file-directory"
app_color = "grey"
app_email = "info@aakvatech.com"
app_license = "MIT"

fixtures = [
    {
        "doctype": "Custom Field",
        "filters": [
            [
                "name",
                "in",
                (
                    "Appointment Type-visit_type_id",
                    "Clinical Procedure Template-healthcare_notes_template",
                    "Clinical Procedure Template-healthcare_service_unit",
                    "Clinical Procedure Template-is_not_available_inhouse",
                    "Clinical Procedure Template-is_not_completed",
                    "Clinical Procedure-approval_number",
                    "Clinical Procedure-approval_type",
                    "Clinical Procedure-healthcare_notes_template",
                    "Clinical Procedure-is_restricted",
                    "Clinical Procedure-mtuha",
                    "Clinical Procedure-pre_operative_note",
                    "Clinical Procedure-pre_operative_notes_template",
                    "Clinical Procedure-procedure_notes",
                    "Clinical Procedure-ref_docname",
                    "Clinical Procedure-ref_doctype",
                    "Clinical Procedure-section_break_0",
                    "Clinical Procedure-section_break_38",
                    "Clinical Procedure-section_break_43",
                    "Clinical Procedure-service_comment",
                    "Codification Table-mtuha",
                    "Delivery Note Item-approval_number",
                    "Delivery Note Item-approval_type",
                    "Delivery Note Item-column_break_89",
                    "Delivery Note Item-healthcare",
                    "Delivery Note Item-is_restricted",
                    "Delivery Note Item-last_date_prescribed",
                    "Delivery Note Item-last_qty_prescribed",
                    "Delivery Note Item-original_item",
                    "Delivery Note Item-original_stock_uom_qty",
                    "Delivery Note Item-recommended_qty",
                    "Delivery Note Item-reference_doctype",
                    "Delivery Note Item-reference_name",
                    "Delivery Note-authorization_number",
                    "Delivery Note-coverage_plan_name",
                    "Delivery Note-healthcare_service_unit",
                    "Delivery Note-medical_department",
                    "Delivery Note-medical_references",
                    "Delivery Note-patient_name",
                    "Delivery Note-patient",
                    "Delivery Note-reference_doctype",
                    "Delivery Note-reference_name",
                    "Descriptive Test Result-result_component_option",
                    "Descriptive Test Template-result_component",
                    "Diet Recommendation-medical_code",
                    "Drug Prescription-amount",
                    "Drug Prescription-cancelled",
                    "Drug Prescription-column_break_34",
                    "Drug Prescription-delivered_quantity",
                    "Drug Prescription-healthcare_service_unit",
                    "Drug Prescription-is_not_available_inhouse",
                    "Drug Prescription-is_restricted",
                    "Drug Prescription-medical_code",
                    "Drug Prescription-override_subscription",
                    "Drug Prescription-prescribe",
                    "Drug Prescription-sales_invoice_number",
                    "Healthcare Insurance Claim-column_break_38",
                    "Healthcare Insurance Claim-insurance_company_item_code",
                    "Healthcare Insurance Claim-insurance_company_item_name",
                    "Healthcare Insurance Claim-ready_to_submit",
                    "Healthcare Insurance Claim-reference_dn",
                    "Healthcare Insurance Claim-reference_dt",
                    "Healthcare Insurance Claim-section_break_35",
                    "Healthcare Insurance Claim-section_break_40",
                    "Healthcare Insurance Company-default_price_list",
                    "Healthcare Insurance Company-facility_code",
                    "Healthcare Insurance Coverage Plan-daily_limit",
                    "Healthcare Insurance Coverage Plan-nhif_scheme_id",
                    "Healthcare Insurance Coverage Plan-secondary_price_list",
                    "Healthcare Insurance Subscription-coverage_plan_card_number",
                    "Healthcare Insurance Subscription-coverage_plan_name",
                    "Healthcare Insurance Subscription-daily_limit",
                    "Healthcare Practitioner-abbreviation",
                    "Healthcare Practitioner-bypass_vitals",
                    "Healthcare Practitioner-default_medication_healthcare_service_unit",
                    "Healthcare Practitioner-default_values",
                    "Healthcare Practitioner-doctors_signature",
                    "Healthcare Practitioner-nhif_physician_qualification",
                    "Healthcare Practitioner-title_and_qualification",
                    "Healthcare Practitioner-tz_mct_code",
                    "Healthcare Service Insurance Coverage-is_auto_generated",
                    "Healthcare Service Insurance Coverage-item",
                    "Healthcare Service Insurance Coverage-maximum_claim_duration",
                    "Healthcare Service Order-clear_insurance_details",
                    "Healthcare Service Order-is_not_billable",
                    "Healthcare Service Order-original_his",
                    "Healthcare Service Order-prescribed",
                    "Healthcare Service Unit Type-is_consultancy_chargeable",
                    "Healthcare Service Unit Type-is_service_chargeable",
                    "Healthcare Service Unit-is_consultancy_chargeable",
                    "Healthcare Service Unit-is_service_chargeable",
                    "Inpatient Consultancy-encounter",
                    "Inpatient Consultancy-is_confirmed",
                    "Inpatient Occupancy-amount",
                    "Inpatient Occupancy-confirmed",
                    "Inpatient Occupancy-delivery_note",
                    "Inpatient Occupancy-is_confirmed",
                    "Inpatient Record-column_break_45",
                    "Inpatient Record-column_break_92",
                    "Inpatient Record-duplicate",
                    "Inpatient Record-duplicated_from",
                    "Inpatient Record-history",
                    "Inpatient Record-inpatient_consultancies",
                    "Inpatient Record-inpatient_consultancy",
                    "Inpatient Record-inpatient_record_final_diagnosis",
                    "Inpatient Record-inpatient_record_preliminary_diagnosis",
                    "Inpatient Record-inpatient_record_type",
                    "Inpatient Record-insurance_coverage_plan",
                    "Inpatient Record-medication",
                    "Inpatient Record-on_examination",
                    "Inpatient Record-patient_appointment",
                    "Inpatient Record-patient_vitals_summary",
                    "Inpatient Record-patient_vitals",
                    "Inpatient Record-practitioner_name",
                    "Inpatient Record-previous_clinical_procedures",
                    "Inpatient Record-previous_diet_recommendation",
                    "Inpatient Record-previous_drug_prescription",
                    "Inpatient Record-previous_lab_tests",
                    "Inpatient Record-previous_radiology_procedure",
                    "Inpatient Record-previous_therapy_plan_detail",
                    "Inpatient Record-price_list",
                    "Inpatient Record-primary_practitioner_name",
                    "Inpatient Record-reference_inpatient_record",
                    "Inpatient Record-reference",
                    "Inpatient Record-review",
                    "Inpatient Record-secondary_practitioner_name",
                    "Inpatient Record-section_break_47",
                    "Inpatient Record-section_break_57",
                    "Inpatient Record-surgical_procedure",
                    "Inpatient Record-when_to_obtain_urgent_care",
                    "Item-healthcare_service_template",
                    "Item-hms_item_name",
                    "Item-recommended_qty",
                    "Lab Prescription-amount",
                    "Lab Prescription-cancelled",
                    "Lab Prescription-column_break_23",
                    "Lab Prescription-delivered_quantity",
                    "Lab Prescription-is_not_available_inhouse",
                    "Lab Prescription-medical_code",
                    "Lab Prescription-override_subscription",
                    "Lab Prescription-prescribe",
                    "Lab Prescription-sales_invoice_number",
                    "Lab Prescription-section_break_21",
                    "Lab Test Template-c_max_range",
                    "Lab Test Template-c_min_range",
                    "Lab Test Template-c_text",
                    "Lab Test Template-column_break_26",
                    "Lab Test Template-column_break_30",
                    "Lab Test Template-column_break_34",
                    "Lab Test Template-f_max_range",
                    "Lab Test Template-f_min_range",
                    "Lab Test Template-f_text",
                    "Lab Test Template-healthcare_service_unit",
                    "Lab Test Template-i_max_range",
                    "Lab Test Template-i_min_range",
                    "Lab Test Template-i_text",
                    "Lab Test Template-is_not_available_inhouse",
                    "Lab Test Template-lab_routine_normals",
                    "Lab Test Template-m_max_range",
                    "Lab Test Template-m_min_range",
                    "Lab Test Template-m_text",
                    "Lab Test-approval_number",
                    "Lab Test-approval_type",
                    "Lab Test-is_restricted",
                    "Lab Test-ref_docname",
                    "Lab Test-ref_doctype",
                    "Lab Test-service_comment",
                    "Lab Test-title",
                    "Lab Test-workflow_state",
                    "Medication-default_comments",
                    "Medication-is_not_available_inhouse",
                    "Medication-strength_text",
                    "Mode of Payment-price_list",
                    "Normal Test Result-detailed_normal_range",
                    "Normal Test Result-max_normal",
                    "Normal Test Result-min_normal",
                    "Normal Test Result-result_status",
                    "Normal Test Result-text_normal",
                    "Patient Appointment-authorization_number",
                    "Patient Appointment-coverage_plan_card_number",
                    "Patient Appointment-coverage_plan_name",
                    "Patient Appointment-daily_limit",
                    "Patient Appointment-follow_up",
                    "Patient Appointment-get_authorization_number",
                    "Patient Appointment-healthcare_referrer_type",
                    "Patient Appointment-healthcare_referrer",
                    "Patient Appointment-insurance_company_name",
                    "Patient Appointment-nhif_patient_claim",
                    "Patient Appointment-old_hms_number",
                    "Patient Appointment-patient_image2",
                    "Patient Appointment-payment_reference",
                    "Patient Appointment-ref_patient_encounter",
                    "Patient Appointment-ref_vital_signs",
                    "Patient Appointment-reference_journal_entry",
                    "Patient Appointment-referral_no",
                    "Patient Appointment-send_vfd",
                    "Patient Encounter Symptom-complaint_comments",
                    "Patient Encounter Symptom-complaint_duration",
                    "Patient Encounter Symptom-compliant_duration",
                    "Patient Encounter Symptom-system",
                    "Patient Encounter-abbr",
                    "Patient Encounter-blood_group",
                    "Patient Encounter-column_break_31",
                    "Patient Encounter-copy_from_preliminary_diagnosis",
                    "Patient Encounter-create_sales_invoice",
                    "Patient Encounter-current_total",
                    "Patient Encounter-daily_limit",
                    "Patient Encounter-default_healthcare_service_unit",
                    "Patient Encounter-duplicated",
                    "Patient Encounter-ed_addressed_to",
                    "Patient Encounter-ed_no_of_days",
                    "Patient Encounter-ed_reason_for_absence",
                    "Patient Encounter-encounter_category",
                    "Patient Encounter-encounter_mode_of_payment",
                    "Patient Encounter-encounter_type",
                    "Patient Encounter-examination_detail",
                    "Patient Encounter-finalized",
                    "Patient Encounter-from_encounter",
                    "Patient Encounter-get_chronic_diagnosis",
                    "Patient Encounter-get_chronic_medications",
                    "Patient Encounter-healthcare_practitioner_signature",
                    "Patient Encounter-healthcare_referrer",
                    "Patient Encounter-healthcare_service_unit",
                    "Patient Encounter-image",
                    "Patient Encounter-insurance_coverage_plan",
                    "Patient Encounter-is_not_billable",
                    "Patient Encounter-mode_of_payment",
                    "Patient Encounter-old_hms_registration_no",
                    "Patient Encounter-patient_encounter_final_diagnosis",
                    "Patient Encounter-patient_encounter_preliminary_diagnosis",
                    "Patient Encounter-patient_info_section_break",
                    "Patient Encounter-patient_signature",
                    "Patient Encounter-previous_diet_recommendation",
                    "Patient Encounter-previous_drug_prescription",
                    "Patient Encounter-previous_lab_prescription",
                    "Patient Encounter-previous_procedure_prescription",
                    "Patient Encounter-previous_radiology_procedure_prescription",
                    "Patient Encounter-previous_therapy_plan_detail",
                    "Patient Encounter-previous_total",
                    "Patient Encounter-reference_encounter",
                    "Patient Encounter-reference",
                    "Patient Encounter-sales_invoice",
                    "Patient Encounter-section_break_28",
                    "Patient Encounter-section_break_52",
                    "Patient Encounter-sent_to_vfd",
                    "Patient Encounter-signatures",
                    "Patient Encounter-symptoms_and_signs",
                    "Patient Encounter-system_and_symptoms",
                    "Patient Encounter-undo_set_as_final",
                    "Patient Referral-referred_to_facility",
                    "Patient-card_no",
                    "Patient-chronic_medications",
                    "Patient-chronic_section",
                    "Patient-codification_table",
                    "Patient-column_break_3",
                    "Patient-insurance_card_detail",
                    "Patient-insurance_details",
                    "Patient-membership_no",
                    "Patient-next_to_kid_column_break",
                    "Patient-next_to_kin_details",
                    "Patient-next_to_kin_mobile_no",
                    "Patient-next_to_kin_name",
                    "Patient-next_to_kin_relationship",
                    "Patient-nida_card_number",
                    "Patient-old_hms_registration_no",
                    "Patient-patient_details_with_formatting",
                    "Patient-product_code",
                    "Prescription Dosage-column_break_1",
                    "Prescription Dosage-default_strength",
                    "Prescription Dosage-dosage_form",
                    "Prescription Dosage-section_break_3",
                    "Previous Therapy Plan Detail-column_break_6",
                    "Print Settings-print_uom_after_quantity",
                    "Procedure Prescription-amount",
                    "Procedure Prescription-cancelled",
                    "Procedure Prescription-column_break_10",
                    "Procedure Prescription-column_break_30",
                    "Procedure Prescription-delivered_quantity",
                    "Procedure Prescription-hso_payment_method",
                    "Procedure Prescription-is_not_available_inhouse",
                    "Procedure Prescription-medical_code",
                    "Procedure Prescription-override_insurance_subscription",
                    "Procedure Prescription-override_subscription",
                    "Procedure Prescription-prescribe",
                    "Procedure Prescription-sales_invoice_number",
                    "Procedure Prescription-section_break_28",
                    "Radiology Examination Template-body_part",
                    "Radiology Examination Template-healthcare_service_unit",
                    "Radiology Examination Template-is_not_available_inhouse",
                    "Radiology Examination Template-radiology_report_details",
                    "Radiology Examination Template-radiology_report_type",
                    "Radiology Examination Template-radiology_report",
                    "Radiology Examination-approval_number",
                    "Radiology Examination-approval_type",
                    "Radiology Examination-body_part",
                    "Radiology Examination-healthcare_practitioner_name",
                    "Radiology Examination-is_restricted",
                    "Radiology Examination-radiology_report_details",
                    "Radiology Examination-radiology_report",
                    "Radiology Examination-ref_docname",
                    "Radiology Examination-ref_doctype",
                    "Radiology Examination-service_comment",
                    "Radiology Procedure Prescription-amount",
                    "Radiology Procedure Prescription-cancelled",
                    "Radiology Procedure Prescription-column_break_25",
                    "Radiology Procedure Prescription-delivered_quantity",
                    "Radiology Procedure Prescription-is_not_available_inhouse",
                    "Radiology Procedure Prescription-medical_code",
                    "Radiology Procedure Prescription-override_subscription",
                    "Radiology Procedure Prescription-prescribe",
                    "Radiology Procedure Prescription-sales_invoice_number",
                    "Radiology Procedure Prescription-section_break_23",
                    "Sales Invoice Item-reference_dn",
                    "Sales Invoice Item-reference_dt",
                    "Sales Invoice-patient_name",
                    "Sales Invoice-patient",
                    "Sales Invoice-ref_practitioner",
                    "Sales Order-patient_actual_name",
                    "Sales Order-patient_mobile_number",
                    "Sample Collection-ref_docname",
                    "Sample Collection-ref_doctype",
                    "Sample Collection-section_break_20",
                    "Stock Entry Detail-inpatient_medication_entry_child",
                    "Stock Entry Detail-patient",
                    "Stock Entry-inpatient_medication_entry",
                    "Therapy Plan Detail-amount",
                    "Therapy Plan Detail-cancelled",
                    "Therapy Plan Detail-column_break_22",
                    "Therapy Plan Detail-column_break_6",
                    "Therapy Plan Detail-comment",
                    "Therapy Plan Detail-delivered_quantity",
                    "Therapy Plan Detail-is_not_available_inhouse",
                    "Therapy Plan Detail-medical_code",
                    "Therapy Plan Detail-override_subscription",
                    "Therapy Plan Detail-prescribe",
                    "Therapy Plan Detail-sales_invoice_number",
                    "Therapy Plan Detail-section_break_20",
                    "Therapy Plan Template-is_not_available_inhouse",
                    "Therapy Plan-ref_docname",
                    "Therapy Plan-ref_doctype",
                    "Therapy Type-is_not_available_inhouse",
                    "Vital Signs-column_break_29",
                    "Vital Signs-eye_opening",
                    "Vital Signs-glasgow_coma_scale",
                    "Vital Signs-healthcare_practitioner",
                    "Vital Signs-height_in_cm",
                    "Vital Signs-image",
                    "Vital Signs-medical_department",
                    "Vital Signs-mode_of_payment",
                    "Vital Signs-motor_response",
                    "Vital Signs-oxygen_saturation_spo2",
                    "Vital Signs-patient_progress",
                    "Vital Signs-patient_vitals_summary",
                    "Vital Signs-patient_vitals",
                    "Vital Signs-practitioner",
                    "Vital Signs-rbg",
                    "Vital Signs-section_break_2",
                    "Vital Signs-verbal_response",
                    "Healthcare Insurance Claim-order_encounter",
                    "Patient-insurance_company",
                    "Medication-ref_doctype",
                    "Medication-ref_docname",
                    "Delivery Note-column_break_21",
                    "Therapy Plan Detail-reference_journal_entry",
                    "Procedure Prescription-reference_journal_entry",
                    "Radiology Procedure Prescription-reference_journal_entry",
                    "Lab Prescription-reference_journal_entry",
                    "Drug Prescription-reference_journal_entry",
                    "Drug Prescription-invoiced",
                    "Therapy Plan Detail-invoiced",
                    "Medication-healthcare_service_unit",
                    "Patient Encounter-get_lab_bundle_items",
                    "Patient Encounter-lab_bundle",
                ),
            ]
        ],
    },
    {
        "doctype": "Property Setter",
        "filters": [
            [
                "name",
                "in",
                (
                    "Appointment Type-main-sort_field",
                    "Appointment Type-main-sort_order",
                    "Chronic Medications-dosage-fetch_if_empty",
                    "Chronic Medications-period-fetch_if_empty",
                    "Clinical Procedure-company-read_only",
                    "Clinical Procedure-insurance_section-hidden",
                    "Clinical Procedure-insurance_subscription-read_only",
                    "Clinical Procedure-main-allow_copy",
                    "Clinical Procedure-main-default_print_format",
                    "Clinical Procedure-medical_department-read_only",
                    "Clinical Procedure-naming_series-options",
                    "Clinical Procedure-patient_name-fetch_from",
                    "Clinical Procedure-patient_name-fetch_if_empty",
                    "Clinical Procedure-patient_name-in_list_view",
                    "Clinical Procedure-patient-read_only",
                    "Clinical Procedure-practitioner_name-in_list_view",
                    "Clinical Procedure-practitioner-mandatory_depends_on",
                    "Clinical Procedure-practitioner-read_only_depends_on",
                    "Clinical Procedure-procedure_template-in_list_view",
                    "Clinical Procedure-procedure_template-read_only",
                    "Clinical Procedure-sample-hidden",
                    "Clinical Procedure-sb_refs-hidden",
                    "Clinical Procedure-sb_source-hidden",
                    "Clinical Procedure-source-read_only",
                    "Clinical Procedure-start_date-hidden",
                    "Clinical Procedure-start_time-hidden",
                    "Delivery Note Item-batch_no-hidden",
                    "Delivery Note Item-description-in_list_view",
                    "Delivery Note Item-item_code-permlevel",
                    "Delivery Note Item-item_name-permlevel",
                    "Delivery Note Item-qty-columns",
                    "Delivery Note Item-rate-in_list_view",
                    "Delivery Note Item-rate-permlevel",
                    "Delivery Note Item-section_break_6-columns",
                    "Delivery Note Item-uom-in_list_view",
                    "Delivery Note Item-warehouse-columns",
                    "Descriptive Test Result-lab_test_particulars-columns",
                    "Descriptive Test Result-lab_test_particulars-fetch_from",
                    "Descriptive Test Result-result_value-fetch_from",
                    "Descriptive Test Result-result_value-fetch_if_empty",
                    "Dosage Strength-strength-label",
                    "Drug Prescription-comment-fetch_from",
                    "Drug Prescription-comment-fetch_if_empty",
                    "Drug Prescription-comment-in_list_view",
                    "Drug Prescription-comment-mandatory_depends_on",
                    "Drug Prescription-dosage_form-fetch_if_empty",
                    "Drug Prescription-dosage-columns",
                    "Drug Prescription-dosage-fetch_if_empty",
                    "Drug Prescription-dosage-reqd",
                    "Drug Prescription-drug_code-columns",
                    "Drug Prescription-drug_name-in_list_view",
                    "Drug Prescription-drug_prescription_created-label",
                    "Drug Prescription-drug_prescription_created-read_only",
                    "Drug Prescription-interval_uom-in_list_view",
                    "Drug Prescription-interval-in_list_view",
                    "Drug Prescription-period-columns",
                    "Drug Prescription-period-fetch_if_empty",
                    "Drug Prescription-period-reqd",
                    "Drug Prescription-quantity-columns",
                    "Drug Prescription-quantity-in_list_view",
                    "Exercise-difficulty_level-fetch_if_empty",
                    "Fees-cost_center-fetch_from",
                    "Fees-income_account-fetch_from",
                    "Fees-receivable_account-fetch_from",
                    "Healthcare Insurance Claim-healthcare_service_type-in_list_view",
                    "Healthcare Insurance Claim-healthcare_service_type-in_standard_filter",
                    "Healthcare Insurance Claim-service_template-in_list_view",
                    "Healthcare Insurance Claim-service_template-in_standard_filter",
                    "Healthcare Insurance Company-customer-read_only",
                    "Healthcare Insurance Subscription-country-hidden",
                    "Healthcare Insurance Subscription-customer-hidden",
                    "Healthcare Insurance Subscription-gender-read_only",
                    "Healthcare Insurance Subscription-insurance_company_customer-hidden",
                    "Healthcare Insurance Subscription-insurance_company_name-in_standard_filter",
                    "Healthcare Insurance Subscription-insurance_company_name-read_only",
                    "Healthcare Insurance Subscription-main-search_fields",
                    "Healthcare Insurance Subscription-patient_name-read_only",
                    "Healthcare Insurance Subscription-patient-allow_on_submit",
                    "Healthcare Insurance Subscription-patient-in_standard_filter",
                    "Healthcare Practitioner-main-search_fields",
                    "Healthcare Practitioner-naming_series-options",
                    "Healthcare Practitioner-practitioner_name-in_global_search",
                    "Healthcare Service Insurance Coverage-end_date-Allow on Submit",
                    "Healthcare Service Insurance Coverage-healthcare_service_template-in_standard_filter",
                    "Healthcare Service Insurance Coverage-healthcare_service-in_standard_filter",
                    "Healthcare Service Insurance Coverage-is_active-allow_on_submit",
                    "Healthcare Service Order-main-allow_copy",
                    "Healthcare Service Order-order_date-in_list_view",
                    "Healthcare Service Order-order_doctype-in_list_view",
                    "Healthcare Service Order-order_group-in_list_view",
                    "Healthcare Service Order-order_group-in_standard_filter",
                    "Healthcare Service Order-order-in_list_view",
                    "Healthcare Service Order-origin_section-hidden",
                    "Healthcare Service Order-patient_name-in_list_view",
                    "Healthcare Service Order-patient-in_standard_filter",
                    "Healthcare Service Order-priority-in_list_view",
                    "Healthcare Service Order-staff_role-in_list_view",
                    "Healthcare Service Order-status-in_list_view",
                    "Inpatient Consultancy-confirmed-hidden",
                    "Inpatient Consultancy-date-columns",
                    "Inpatient Occupancy-check_in-columns",
                    "Inpatient Occupancy-check_in-read_only",
                    "Inpatient Occupancy-check_out-in_list_view",
                    "Inpatient Occupancy-check_out-read_only",
                    "Inpatient Occupancy-invoiced-read_only",
                    "Inpatient Occupancy-left-in_list_view",
                    "Inpatient Occupancy-left-read_only",
                    "Inpatient Occupancy-service_unit-read_only",
                    "Inpatient Record-admitted_datetime-in_list_view",
                    "Inpatient Record-company-read_only",
                    "Inpatient Record-diagnosis-hidden",
                    "Inpatient Record-diet_recommendation_section-collapsible",
                    "Inpatient Record-diet_recommendation_section-hidden",
                    "Inpatient Record-discharge_ordered_date-in_list_view",
                    "Inpatient Record-drug_prescription-label",
                    "Inpatient Record-drug_prescription-permlevel",
                    "Inpatient Record-encounter_details_section-collapsible",
                    "Inpatient Record-expected_discharge-in_list_view",
                    "Inpatient Record-inpatient_occupancies-read_only",
                    "Inpatient Record-insurance_subscription-fetch_from",
                    "Inpatient Record-insurance_subscription-fetch_if_empty",
                    "Inpatient Record-investigations_section-collapsible",
                    "Inpatient Record-investigations_section-collapsible_depends_on",
                    "Inpatient Record-investigations_section-hidden",
                    "Inpatient Record-investigations_section-label",
                    "Inpatient Record-lab_test_prescription-label",
                    "Inpatient Record-medication_section-collapsible",
                    "Inpatient Record-medication_section-collapsible_depends_on",
                    "Inpatient Record-medication_section-hidden",
                    "Inpatient Record-medication_section-label",
                    "Inpatient Record-naming_series-options",
                    "Inpatient Record-patient_name-in_list_view",
                    "Inpatient Record-procedure_prescription-label",
                    "Inpatient Record-procedures_section-collapsible",
                    "Inpatient Record-procedures_section-collapsible_depends_on",
                    "Inpatient Record-procedures_section-hidden",
                    "Inpatient Record-procedures_section-label",
                    "Inpatient Record-radiology_orders_section-collapsible",
                    "Inpatient Record-radiology_orders_section-collapsible_depends_on",
                    "Inpatient Record-radiology_orders_section-hidden",
                    "Inpatient Record-references-collapsible",
                    "Inpatient Record-rehabilitation_section-collapsible",
                    "Inpatient Record-rehabilitation_section-collapsible_depends_on",
                    "Inpatient Record-rehabilitation_section-hidden",
                    "Item-customer_details-collapsible",
                    "Item-customer_details-collapsible_depends_on",
                    "Journal Entry-letter_head-fetch_from",
                    "Lab Prescription-lab_test_comment-mandatory_depends_on",
                    "Lab Test-company-read_only",
                    "Lab Test-insurance_section-hidden",
                    "Lab Test-lab_test_comment-read_only",
                    "Lab Test-main-default_print_format",
                    "Lab Test-main-title_field",
                    "Lab Test-naming_series-options",
                    "Lab Test-patient_name-allow_on_submit",
                    "Lab Test-patient_name-in_standard_filter",
                    "Lab Test-patient_name-report_hide",
                    "Lab Test-practitioner-in_standard_filter",
                    "Lab Test-practitioner-read_only",
                    "Lab Test-sb_comments-collapsible",
                    "Lab Test-section_break_50-hidden",
                    "Lab Test-source-read_only",
                    "Medical Code-description-in_standard_filter",
                    "Medication Change Request-healthcare_practitioner-in_standard_filter",
                    "Medication Change Request-patient_name-in_list_view",
                    "Medication Change Request-patient_name-in_standard_filter",
                    "Medication Change Request-patient-in_list_view",
                    "Medication Change Request-practitioner_name-in_list_view",
                    "Medication Change Request-practitioner_name-in_standard_filter",
                    "Medication-main-search_fields",
                    "NHIF Patient Claim Disease-date_created-permlevel",
                    "NHIF Patient Claim Disease-disease_code-fetch_from",
                    "NHIF Patient Claim Disease-disease_code-fetch_if_empty",
                    "NHIF Patient Claim-allow_changes-permlevel",
                    "NHIF Patient Claim-authorization_no-permlevel",
                    "NHIF Patient Claim-authorization_no-read_only_depends_on",
                    "NHIF Patient Claim-naming_series-options",
                    "NHIF Response Log-naming_series-options",
                    "Normal Test Result-normal_range-columns",
                    "Normal Test Result-result_value-depends_on",
                    "Patient Appointment-appointment_type-default",
                    "Patient Appointment-claim_status-hidden",
                    "Patient Appointment-duration-hidden",
                    "Patient Appointment-duration-read_only",
                    "Patient Appointment-insurance_claim-hidden",
                    "Patient Appointment-insurance_company-hidden",
                    "Patient Appointment-main-default_print_format",
                    "Patient Appointment-main-image_field",
                    "Patient Appointment-naming_series-hidden",
                    "Patient Appointment-naming_series-options",
                    "Patient Appointment-paid_amount-read_only",
                    "Patient Appointment-practitioner_availability-hidden",
                    "Patient Appointment-practitioner_name-hidden",
                    "Patient Appointment-radiology_examination_template-depends_on",
                    "Patient Appointment-sb_source-depends_on",
                    "Patient Appointment-section_break_19-hidden",
                    "Patient Appointment-service_unit-read_only",
                    "Patient Appointment-status-hidden",
                    "Patient Encounter-appointment_type-default",
                    "Patient Encounter-appointment_type-hidden",
                    "Patient Encounter-appointment_type-mandatory_depends_on",
                    "Patient Encounter-appointment_type-read_only",
                    "Patient Encounter-appointment_type-read_only_depends_on",
                    "Patient Encounter-appointment-hidden",
                    "Patient Encounter-codification-collapsible",
                    "Patient Encounter-codification-hidden",
                    "Patient Encounter-company-hidden",
                    "Patient Encounter-company-read_only",
                    "Patient Encounter-diagnosis_in_print-hidden",
                    "Patient Encounter-diagnosis-hidden",
                    "Patient Encounter-diagnosis-permlevel",
                    "Patient Encounter-diet_recommendation_section-collapsible",
                    "Patient Encounter-diet_recommendation_section-collapsible_depends_on",
                    "Patient Encounter-encounter_comment-hidden",
                    "Patient Encounter-encounter_date-in_list_view",
                    "Patient Encounter-encounter_date-read_only",
                    "Patient Encounter-encounter_time-in_list_view",
                    "Patient Encounter-encounter_time-read_only",
                    "Patient Encounter-finalized-in_list_view",
                    "Patient Encounter-inpatient_record-permlevel",
                    "Patient Encounter-inpatient_status-permlevel",
                    "Patient Encounter-insurance_coverage_plan-in_list_view",
                    "Patient Encounter-insurance_section-hidden",
                    "Patient Encounter-insurance_subscription-read_only",
                    "Patient Encounter-main-image_field",
                    "Patient Encounter-medical_department-hidden",
                    "Patient Encounter-medical_department-in_list_view",
                    "Patient Encounter-naming_series-hidden",
                    "Patient Encounter-patient_name-hidden",
                    "Patient Encounter-patient_sex-hidden",
                    "Patient Encounter-patient_vitals_summary_section-permlevel",
                    "Patient Encounter-patient_vitals-permlevel",
                    "Patient Encounter-patient-default",
                    "Patient Encounter-physical_examination-hidden",
                    "Patient Encounter-practitioner_name-in_list_view",
                    "Patient Encounter-practitioner-default",
                    "Patient Encounter-practitioner-mandatory_depends_on",
                    "Patient Encounter-radiology_procedures_section-collapsible",
                    "Patient Encounter-radiology_procedures_section-collapsible_depends_on",
                    "Patient Encounter-rehabilitation_section-collapsible",
                    "Patient Encounter-rehabilitation_section-collapsible_depends_on",
                    "Patient Encounter-sb_drug_prescription-collapsible",
                    "Patient Encounter-sb_drug_prescription-collapsible_depends_on",
                    "Patient Encounter-sb_procedures-collapsible",
                    "Patient Encounter-sb_procedures-collapsible_depends_on",
                    "Patient Encounter-sb_source-collapsible",
                    "Patient Encounter-sb_symptoms-hidden",
                    "Patient Encounter-sb_symptoms-permlevel",
                    "Patient Encounter-sb_test_prescription-collapsible",
                    "Patient Encounter-sb_test_prescription-collapsible_depends_on",
                    "Patient Encounter-section_break_3-collapsible",
                    "Patient Encounter-section_break_33-permlevel",
                    "Patient Encounter-sort_field",
                    "Patient Encounter-sort_order",
                    "Patient Encounter-source-read_only_depends_on",
                    "Patient Encounter-symptoms_in_print-hidden",
                    "Patient Encounter-symptoms-permlevel",
                    "Patient Encounter-title-in_list_view",
                    "Patient Encounter-triage-hidden",
                    "Patient Encounter-triage-permlevel",
                    "Patient-allergies-in_preview",
                    "Patient-allergies-permlevel",
                    "Patient-allergy_medical_and_surgical_history-collapsible",
                    "Patient-allergy_medical_and_surgical_history-permlevel",
                    "Patient-customer_group-default",
                    "Patient-default_currency-read_only",
                    "Patient-default_price_list-hidden",
                    "Patient-first_name-read_only_depends_on",
                    "Patient-invite_user-default",
                    "Patient-main-quick_entry",
                    "Patient-medical_history-hidden",
                    "Patient-medical_history-in_preview",
                    "Patient-medical_history-permlevel",
                    "Patient-medical_history-read_only",
                    "Patient-medication-hidden",
                    "Patient-medication-in_preview",
                    "Patient-medication-permlevel",
                    "Patient-medication-read_only",
                    "Patient-mobile-reqd",
                    "Patient-more_info-collapsible_depends_on",
                    "Patient-patient_details-hidden",
                    "Patient-patient_name-in_preview",
                    "Patient-personal_and_social_history-collapsible",
                    "Patient-personal_and_social_history-permlevel",
                    "Patient-risk_factors-collapsible",
                    "Patient-risk_factors-permlevel",
                    "Patient-sb_relation-hidden",
                    "Patient-search_fields",
                    "Patient-show_preview_popup",
                    "Patient-surgical_history-in_preview",
                    "Patient-surgical_history-permlevel",
                    "Patient-territory-hidden",
                    "Patient-triage-hidden",
                    "POS Profile-update_stock-default",
                    "POS Profile-warehouse-depends_on",
                    "Practitioner Availability Type-main-allow_rename",
                    "Practitioner Availability-availability-in_list_view",
                    "Practitioner Availability-main-allow_copy",
                    "Practitioner Availability-main-allow_rename",
                    "Practitioner Availability-practitioner-in_list_view",
                    "Practitioner Availability-practitioner-in_standard_filter",
                    "Practitioner Availability-to_date-in_list_view",
                    "Prescription Dosage-main-quick_entry",
                    "Procedure Prescription-comments-mandatory_depends_on",
                    "Purchase Invoice-payment_schedule-print_hide",
                    "Purchase Order-due_date-print_hide",
                    "Purchase Order-payment_schedule-print_hide",
                    "Radiology Examination Template-disabled-in_standard_filter",
                    "Radiology Examination Template-item-in_standard_filter",
                    "Radiology Examination Template-main-allow_rename",
                    "Radiology Examination Template-main-quick_entry",
                    "Radiology Examination-appointment-hidden",
                    "Radiology Examination-appointment-in_list_view",
                    "Radiology Examination-insurance_section-hidden",
                    "Radiology Examination-insurance_section-read_only",
                    "Radiology Examination-main-default_print_format",
                    "Radiology Examination-medical_department-read_only",
                    "Radiology Examination-patient_name-fetch_from",
                    "Radiology Examination-patient_name-in_list_view",
                    "Radiology Examination-patient_name-in_standard_filter",
                    "Radiology Examination-patient-read_only",
                    "Radiology Examination-practitioner-in_standard_filter",
                    "Radiology Examination-practitioner-read_only",
                    "Radiology Examination-radiology_examination_template-in_list_view",
                    "Radiology Examination-radiology_examination_template-read_only",
                    "Radiology Examination-source-read_only",
                    "Radiology Examination-start_date-read_only",
                    "Radiology Examination-start_time-read_only",
                    "Radiology Examination-tc_name-fetch_from",
                    "Radiology Examination-tc_name-hidden",
                    "Radiology Examination-terms-hidden",
                    "Radiology Procedure Prescription-radiology_test_comment-mandatory_depends_on",
                    "Sales Invoice Item-item_code-permlevel",
                    "Sales Invoice Item-item_tax_template-fetch_from",
                    "Sales Invoice Item-qty-permlevel",
                    "Sales Invoice Item-rate-permlevel",
                    "Sales Invoice-accounting_dimensions_section-hidden",
                    "Sales Invoice-address_and_contact-depends_on",
                    "Sales Invoice-column_break4-permlevel",
                    "Sales Invoice-customer_po_details-depends_on",
                    "Sales Invoice-customer_po_details-permlevel",
                    "Sales Invoice-debit_to-permlevel",
                    "Sales Invoice-due_date-print_hide",
                    "Sales Invoice-edit_printing_settings-depends_on",
                    "Sales Invoice-is_pos-default",
                    "Sales Invoice-is_return-permlevel",
                    "Sales Invoice-loyalty_points_redemption-hidden",
                    "Sales Invoice-more_info-depends_on",
                    "Sales Invoice-payment_schedule_section-depends_on",
                    "Sales Invoice-payment_schedule-print_hide",
                    "Sales Invoice-sales_team_section_break-depends_on",
                    "Sales Invoice-sales_team_section_break-hidden",
                    "Sales Invoice-section_break2-hidden",
                    "Sales Invoice-set_posting_time-permlevel",
                    "Sales Invoice-set_warehouse-permlevel",
                    "Sales Invoice-shipping_rule-depends_on",
                    "Sales Invoice-subscription_section-depends_on",
                    "Sales Invoice-subscription_section-read_only",
                    "Sales Invoice-tax_category-depends_on",
                    "Sales Invoice-terms_section_break-depends_on",
                    "Sales Invoice-time_sheet_list-hidden",
                    "Sales Invoice-update_stock-depends_on",
                    "Sales Order-due_date-print_hide",
                    "Sales Order-payment_schedule-print_hide",
                    "Shift Type-last_sync_of_checkin-in_list_view",
                    "Therapy Plan-company-read_only",
                    "Therapy Plan-patient_name-in_list_view",
                    "Therapy Plan-patient-read_only",
                    "Therapy Type-main-allow_rename",
                    "Vital Signs-abdomen-hidden",
                    "Vital Signs-height-hidden",
                    "Vital Signs-main-allow_rename",
                    "Vital Signs-main-image_field",
                    "Vital Signs-patient_name-in_standard_filter",
                    "Vital Signs-patient-in_list_view",
                    "Vital Signs-patient-read_only_depends_on",
                    "Vital Signs-reflexes-hidden",
                    "Vital Signs-tongue-hidden",
                    "Patient Encounter-insurance_section-collapsible",
                    "Descriptive Test Result-result_value-hidden",
                    "Descriptive Test Result-result_value-in_list_view",
                    "Descriptive Test Result-result_value-read_only",
                    "Radiology Examination-healthcare_practitioner_name",
                    "Lab Test-lab_test_name-in_list_view",
                    "Lab Test-patient_name-in_list_view",
                    "Delivery Note-items-permlevel",
                    "Inpatient Consultancy-confirmed-permlevel",
                    "Radiology Examination-practitioner-in_standard_filter",
                    "Therapy Plan Detail-invoiced-allow_on_submit",
                    "Drug Prescription-invoiced-allow_on_submit",
                    "Procedure Prescription-invoiced-allow_on_submit",
                    "Radiology Procedure Prescription-invoiced-allow_on_submit",
                    "Lab Prescription-invoiced-allow_on_submit",
                ),
            ]
        ],
    },
    {
        "doctype": "Accounting Dimension",
        "filters": [
            [
                "name",
                "in",
                (
                    "Healthcare Practitioner",
                    "Healthcare Service Unit",
                ),
            ]
        ],
    },
]

# Includes in <head>
# ------------------

# include js, css files in header of desk.html
# app_include_css = "/assets/hms_tz/css/hms_tz.css"
# app_include_js = "/assets/hms_tz/js/hms_tz.js"

# include js, css files in header of web template
# web_include_css = "/assets/hms_tz/css/hms_tz.css"
# web_include_js = "/assets/hms_tz/js/hms_tz.js"

# include custom scss in every website theme (without file extension ".scss")
# website_theme_scss = "hms_tz/public/scss/website"

# include js, css files in header of web form
# webform_include_js = {"doctype": "public/js/doctype.js"}
# webform_include_css = {"doctype": "public/css/doctype.css"}

# include js in page
# page_js = {"page" : "public/js/file.js"}

# include js in doctype views
doctype_js = {
    "Patient Appointment": "nhif/api/patient_appointment.js",
    "Patient": "nhif/api/patient.js",
    "Sales Order": "nhif/api/sales_order.js",
    "Sales Invoice": "nhif/api/sales_invoice.js",
    "Patient Encounter": "nhif/api/patient_encounter.js",
    "Lab Test": "nhif/api/lab_test.js",
    "Healthcare Service Order": "nhif/api/service_order.js",
    "Healthcare Insurance Company": "nhif/api/insurance_company.js",
    "Vital Signs": "nhif/api/vital_signs.js",
    "Healthcare Insurance Subscription": "nhif/api/insurance_subscription.js",
    "Inpatient Record": "nhif/api/inpatient_record.js",
    "Healthcare Service Unit": "nhif/api/service_unit.js",
}
# csf_tz.nhif.api.patient_appointment
# doctype_list_js = {"doctype" : "public/js/doctype_list.js"}
inpatient_record_list_js = {"doctype": "nhif/api/inpatient_record_list.js"}
# doctype_tree_js = {"doctype" : "public/js/doctype_tree.js"}
# doctype_calendar_js = {"doctype" : "public/js/doctype_calendar.js"}

# Home Pages
# ----------

# application home page (will override Website Settings)
# home_page = "login"

# website user home page (by Role)
# role_home_page = {
# 	"Role": "home_page"
# }

# Website user home page (by function)
# get_website_user_home_page = "hms_tz.utils.get_home_page"

# Generators
# ----------

# automatically create page for each record of this doctype
# website_generators = ["Web Page"]

# Installation
# ------------

# before_install = "hms_tz.install.before_install"
# after_install = "hms_tz.install.after_install"

# Desk Notifications
# ------------------
# See frappe.core.notifications.get_notification_config

# notification_config = "hms_tz.notifications.get_notification_config"

# Permissions
# -----------
# Permissions evaluated in scripted ways

# permission_query_conditions = {
# 	"Event": "frappe.desk.doctype.event.event.get_permission_query_conditions",
# }
#
# has_permission = {
# 	"Event": "frappe.desk.doctype.event.event.has_permission",
# }

# DocType Class
# ---------------
# Override standard doctype classes

# override_doctype_class = {
# 	"ToDo": "custom_app.overrides.CustomToDo"
# }

# Document Events
# ---------------
# Hook on document methods and events

doc_events = {
    "Patient Appointment": {
        "validate": [
            "hms_tz.nhif.api.patient_appointment.make_next_doc",
        ]
    },
    "Vital Signs": {
        "on_submit": "hms_tz.nhif.api.patient_appointment.make_encounter",
    },
    "Patient": {
        "validate": "hms_tz.nhif.api.patient.validate",
        "after_insert": "hms_tz.nhif.api.patient.after_insert",
    },
    "Healthcare Insurance Claim": {
        "before_insert": [
            "hms_tz.nhif.api.insurance_claim.set_patient_encounter",
            "hms_tz.nhif.api.insurance_claim.set_price",
        ]
    },
    "Patient Encounter": {
        "before_submit": "hms_tz.nhif.api.patient_encounter.before_submit",
        "after_insert": "hms_tz.nhif.api.patient_encounter.after_insert",
        "validate": "hms_tz.nhif.api.patient_encounter.on_submit_validation",
        "on_trash": "hms_tz.nhif.api.patient_encounter.on_trash",
        "on_submit": "hms_tz.nhif.api.patient_encounter.on_submit",
        # "on_update_after_submit": "hms_tz.nhif.api.patient_encounter.on_update_after_submit",
    },
    "Healthcare Service Order": {
        "before_insert": "hms_tz.nhif.api.service_order.set_missing_values",
    },
    "Sales Invoice": {
        "before_submit": "hms_tz.nhif.api.sales_invoice.before_submit",
        "on_submit": "hms_tz.nhif.api.sales_invoice.on_submit",
        "validate": "hms_tz.nhif.api.sales_invoice.validate",
    },
    "Healthcare Insurance Subscription": {
        "before_insert": "hms_tz.nhif.api.insurance_subscription.before_insert",
        "on_submit": "hms_tz.nhif.api.insurance_subscription.on_submit",
        "before_cancel": "hms_tz.nhif.api.insurance_subscription.on_cancel",
    },
    "Practitioner Availability": {
        "validate": "hms_tz.nhif.api.practitioner_availability.validate",
        "on_trash": "hms_tz.nhif.api.practitioner_availability.on_trash",
    },
    "Lab Test": {
        "on_submit": "hms_tz.nhif.api.lab_test.on_submit",
        "after_insert": "hms_tz.nhif.api.lab_test.after_insert",
        "on_trash": "hms_tz.nhif.api.lab_test.on_trash",
        "validate": "hms_tz.nhif.api.lab_test.validate",
    },
    "Radiology Examination": {
        "on_submit": "hms_tz.nhif.api.radiology_examination.on_submit",
        "validate": "hms_tz.nhif.api.radiology_examination.validate",
    },
    "Clinical Procedure": {
        "on_submit": "hms_tz.nhif.api.clinical_procedure.on_submit",
        "validate": "hms_tz.nhif.api.clinical_procedure.validate",
    },
    "Delivery Note": {
        "validate": "hms_tz.nhif.api.delivery_note.validate",
        "onload": "hms_tz.nhif.api.delivery_note.onload",
        "after_insert": "hms_tz.nhif.api.delivery_note.after_insert",
        "before_submit": "hms_tz.nhif.api.delivery_note.before_submit",
        "on_submit": "hms_tz.nhif.api.delivery_note.on_submit",
    },
    "Inpatient Record": {
        "validate": "hms_tz.nhif.api.inpatient_record.validate",
    },
    "Prescription Dosage": {
        "before_insert": "hms_tz.nhif.api.prescription_dosage.before_insert",
    },
}

# standard_queries = {
# 	"Healthcare Practitioner": "hms_tz.nhif.api.healthcare_practitioner.get_practitioner_list"
# }

# Scheduled Tasks
# ---------------

scheduler_events = {
    # 	"all": [
    # 		"hms_tz.tasks.all"
    # 	],
    "cron": {"*/1 * * * *": ["hms_tz.nhif.api.service_order.real_auto_submit"]},
    "hourly": ["hms_tz.nhif.api.healthcare_utils.set_uninvoiced_so_closed"],
    "daily": ["hms_tz.nhif.api.inpatient_record.daily_update_inpatient_occupancies"],
    # 	"hourly": [
    # 		"hms_tz.tasks.hourly"
    # 	],
    # 	"weekly": [
    # 		"hms_tz.tasks.weekly"
    # 	]
    # 	"monthly": [
    # 		"hms_tz.tasks.monthly"
    # 	]
}

jenv = {"methods": ["get_item_rate:hms_tz.nhif.api.healthcare_utils.get_item_rate"]}


# Testing
# -------

# before_tests = "hms_tz.install.before_tests"

# Overriding Methods
# ------------------------------
#
# override_whitelisted_methods = {
# 	"frappe.desk.doctype.event.event.get_events": "hms_tz.event.get_events"
# }
#
# each overriding function accepts a `data` argument;
# generated from the base implementation of the doctype dashboard,
# along with any modifications made in other Frappe apps
# override_doctype_dashboards = {
# 	"Task": "hms_tz.task.get_dashboard_data"
# }

# exempt linked doctypes from being automatically cancelled
#
# auto_cancel_exempted_doctypes = ["Auto Repeat"]
